"""Git worktree management for per-agent isolated workspaces.

Worktrees live inside the project's .agentx/ folder so all agent system
metadata stays self-contained.  A .gitignore is written inside .agentx/ to
exclude the worktrees/ sub-directory from the outer repository.

Each specialist gets its own git branch + worktree; they are merged back into
the base branch and removed immediately after a successful merge.
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_AGENTX_GITIGNORE_CONTENT = """\
# Auto-generated by agentx — do not edit by hand.
# Keeps agent runtime data out of your repository.
# agent_config.yml is intentionally NOT ignored so you can commit your config.
worktrees/
agent_storage/
*.log
__pycache__/
"""


class WorktreeManager:
    """Create, track, merge, and auto-clean per-agent git worktrees.

    Worktrees are placed at  ``<repo>/.agentx/worktrees/<agent_name>/``
    so all agent state stays inside the .agentx folder.  Each worktree is
    removed as soon as its branch is successfully merged.

    Parameters
    ----------
    repo_dir:
        Root directory of the git repository (contains or will contain .git).
    base_branch:
        Branch specialist branches diverge from and merge back into.
    """

    def __init__(self, repo_dir: str | Path, base_branch: str = "main") -> None:
        self._repo        = Path(repo_dir).resolve()
        self._base_branch = base_branch
        self._agentx_dir  = self._repo / ".agentx"
        self._wt_base     = self._agentx_dir / "worktrees"
        # agent_name -> (branch_name, worktree_path)
        self._worktrees: dict[str, tuple[str, Path]] = {}

    # ------------------------------------------------------------------
    # Setup
    # ------------------------------------------------------------------

    def ensure_repo(self) -> None:
        """Ensure the workspace is a git repo, then write .agentx/.gitignore."""
        self._repo.mkdir(parents=True, exist_ok=True)
        self._wt_base.mkdir(parents=True, exist_ok=True)
        self._write_agentx_gitignore()

        if (self._repo / ".git").exists():
            logger.debug("Git repo exists at %s", self._repo)
            self._ensure_branch()
            return

        logger.info("Initialising git repo at %s", self._repo)
        self._run("init", "-b", self._base_branch)
        # Stage everything except what .gitignore excludes, then commit
        self._run("add", "-A")
        result = self._run_raw("diff", "--cached", "--quiet")
        if result.returncode != 0:
            self._run("commit", "-m", "chore: initial workspace commit")
        else:
            self._run("commit", "--allow-empty", "-m", "chore: initial workspace commit")

    def _write_agentx_gitignore(self) -> None:
        """Write/refresh .agentx/.gitignore (idempotent)."""
        gi = self._agentx_dir / ".gitignore"
        gi.write_text(_AGENTX_GITIGNORE_CONTENT, encoding="utf-8")
        logger.debug("Wrote %s", gi)

    def _ensure_branch(self) -> None:
        current = self._run("branch", "--show-current").strip()
        if not current:
            self._run("checkout", "-B", self._base_branch)

    # ------------------------------------------------------------------
    # Worktree lifecycle
    # ------------------------------------------------------------------

    def create_worktree(self, agent_name: str) -> Path:
        """Create a branch + worktree for a specialist agent.

        The worktree is placed at ``<repo>/.agentx/worktrees/<agent_name>/``.
        Stale worktrees from prior runs are removed and recreated.

        Returns:
            Absolute path to the worktree directory.
        """
        branch        = f"agent/{agent_name}"
        worktree_path = self._wt_base / agent_name
        worktree_path.parent.mkdir(parents=True, exist_ok=True)

        # Remove stale state from a previous run
        self._cleanup_one(agent_name, silent=True)

        self._run("branch", branch)
        self._run("worktree", "add", str(worktree_path), branch)

        self._worktrees[agent_name] = (branch, worktree_path)
        logger.info("Worktree created: %s → %s", branch, worktree_path)
        return worktree_path

    def worktree_path(self, agent_name: str) -> Path | None:
        entry = self._worktrees.get(agent_name)
        return entry[1] if entry else None

    # ------------------------------------------------------------------
    # Merge + auto-cleanup
    # ------------------------------------------------------------------

    def merge_all(self) -> str:
        """Merge every specialist branch, then remove its worktree immediately.

        Each worktree is auto-committed if uncommitted changes remain, merged
        into the base branch, and then deleted.  The cleanup happens per-agent
        so disk space is reclaimed as soon as each branch lands.

        Returns:
            Human-readable per-agent merge summary.
        """
        if not self._worktrees:
            return "No agent worktrees to merge."

        lines: list[str] = []
        for agent_name, (branch, wt_path) in list(self._worktrees.items()):
            # 1. Auto-commit anything the specialist left uncommitted
            self._auto_commit_worktree(agent_name, wt_path, branch)

            # 2. Merge into base branch
            try:
                self._run(
                    "merge", "--no-ff", branch,
                    "-m", f"Merge specialist/{agent_name} results",
                )
                lines.append(f"✓ {agent_name}: merged successfully.")
                logger.info("Merged %s", branch)
            except subprocess.CalledProcessError as exc:
                err = (exc.stderr or exc.stdout or str(exc)).strip()
                lines.append(f"✗ {agent_name}: merge conflict — {err[:200]}")
                self._run_raw("merge", "--abort")
                logger.warning("Merge conflict for %s: %s", agent_name, err)

            # 3. Remove worktree + branch immediately after merge attempt
            self._cleanup_one(agent_name)

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def cleanup(self) -> None:
        """Remove all remaining worktrees (call if merge_all was not used)."""
        for agent_name in list(self._worktrees):
            self._cleanup_one(agent_name)
        self._worktrees.clear()
        logger.info("All agent worktrees removed.")

    def _cleanup_one(self, agent_name: str, *, silent: bool = False) -> None:
        branch        = f"agent/{agent_name}"
        worktree_path = self._wt_base / agent_name

        self._run_raw("worktree", "remove", str(worktree_path), "--force")
        self._run_raw("branch", "-D", branch)
        self._worktrees.pop(agent_name, None)

        if not silent:
            logger.info("Removed worktree and branch for %s", agent_name)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _auto_commit_worktree(self, agent_name: str, wt_path: Path, branch: str) -> None:
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, cwd=wt_path,
        )
        if not status.stdout.strip():
            return
        subprocess.run(["git", "add", "-A"], cwd=wt_path, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", f"feat({agent_name}): agent work output"],
            cwd=wt_path, check=True, capture_output=True,
        )
        logger.debug("Auto-committed changes for %s", agent_name)

    def _run(self, *args: str) -> str:
        result = subprocess.run(
            ["git", *args],
            capture_output=True, text=True, cwd=self._repo, check=True,
        )
        return result.stdout

    def _run_raw(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args],
            capture_output=True, text=True, cwd=self._repo,
        )
